#!/bin/sh
#
# SOME REQUIRED STUFF
#

CWD=`dirname $0`
ROOT_DIR=$1
DIST="common"

if [ ! -d ${ROOT_DIR} ]; then
	exit 1
fi

chroot ${ROOT_DIR} apt-get update

if [ -n "${DIST}" ] && [ -d ${CWD}/${DIST}.d ]; then
	for script in `find ${CWD}/${DIST}.d -type f | sort`; do
		${script} ${ROOT_DIR}
	done
fi
