#!/bin/sh
#
#  This script ensures that daemons will not be started inside our
# chroot() installation.
#
# Steve
# --
# http://www.steve.org.uk/

prefix=$1

#
#  Make sure we have a directory.
#
if [ ! -d "${prefix}/usr/sbin" ]; then

    mkdir -p "${prefix}/usr/sbin"
fi

#
#  Add the script.
#
echo '#!/bin/sh' >  ${prefix}/usr/sbin/policy-rc.d
echo 'exit 101'  >> ${prefix}/usr/sbin/policy-rc.d
chmod 755           ${prefix}/usr/sbin/policy-rc.d
