#!/bin/sh

prefix=$1

chroot ${prefix} apt-get install -y sysvinit-core sysvinit sysvinit-utils
chroot ${prefix} apt-get remove -y --purge --auto-remove systemd
chroot ${prefix} echo -e 'Package: systemd\nPin: origin ""\nPin-Priority: -1' > /etc/apt/preferences.d/systemd
