#!/bin/sh
#
#  This script ensures the new image has locales setup correctly.
#
# Steve
# --
# http://www.steve.org.uk/

prefix=$1

#
# Default to the same locale as the host.
#
if [ -e /etc/locale.gen ]; then
   cp /etc/locale.gen ${prefix}/etc
fi

#
#  Install the package
#
chroot ${prefix} /usr/bin/apt-get install -y locales
chroot ${prefix} /usr/bin/apt-get install -y  util-linux-locales
chroot ${prefix} /usr/sbin/update-locale LANG=C LC_ALL=C
