#!/bin/sh
#
#  This script disables the hardware clock.
#
# Steve
# --
# http://www.steve.org.uk/

prefix=$1

#
#  Disable the startup scripts from all runlevels.
#
chroot ${prefix} /usr/sbin/update-rc.d -f hwclock.sh remove
